-- Support for service request tickets generated by technicians on-site
ALTER TABLE pm_tickets ADD COLUMN IF NOT EXISTS parent_ticket_id UUID REFERENCES pm_tickets(id);
ALTER TABLE pm_tickets ADD COLUMN IF NOT EXISTS ticket_type VARCHAR DEFAULT 'pm' CHECK (ticket_type IN ('pm', 'service_request'));
